main = "./src/index.ts"
name = "partycalendar"
compatibility_date = "2024-11-11"
routes = [
	{ pattern = "cons.furcw.fun/*", custom_domain = true }
]
[observability.logs]
enabled = true

[triggers]
crons = ["0 0 0 * * ? *"]

[build]
command = "npm install;npm run build"
watch_dir = "src"

[env]
DATA_SOORCE = "https://api.furrycons.cn/event/recent"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "cons-calendar"
database_id = "bbb46772-1d07-4094-9ff6-0ec62d9614b2"
